// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: services/dependency_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DependencyServiceCode int32

const (
	DependencyServiceCode_SYNC      DependencyServiceCode = 0
	DependencyServiceCode_INSTALL   DependencyServiceCode = 1
	DependencyServiceCode_UNINSTALL DependencyServiceCode = 2
	DependencyServiceCode_SETUP     DependencyServiceCode = 3
)

// Enum value maps for DependencyServiceCode.
var (
	DependencyServiceCode_name = map[int32]string{
		0: "SYNC",
		1: "INSTALL",
		2: "UNINSTALL",
		3: "SETUP",
	}
	DependencyServiceCode_value = map[string]int32{
		"SYNC":      0,
		"INSTALL":   1,
		"UNINSTALL": 2,
		"SETUP":     3,
	}
)

func (x DependencyServiceCode) Enum() *DependencyServiceCode {
	p := new(DependencyServiceCode)
	*p = x
	return p
}

func (x DependencyServiceCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyServiceCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_dependency_service_proto_enumTypes[0].Descriptor()
}

func (DependencyServiceCode) Type() protoreflect.EnumType {
	return &file_services_dependency_service_proto_enumTypes[0]
}

func (x DependencyServiceCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyServiceCode.Descriptor instead.
func (DependencyServiceCode) EnumDescriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{0}
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{0}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DependencyServiceConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
}

func (x *DependencyServiceConnectRequest) Reset() {
	*x = DependencyServiceConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyServiceConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyServiceConnectRequest) ProtoMessage() {}

func (x *DependencyServiceConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyServiceConnectRequest.ProtoReflect.Descriptor instead.
func (*DependencyServiceConnectRequest) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{1}
}

func (x *DependencyServiceConnectRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

type DependencyServiceConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       DependencyServiceCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.DependencyServiceCode" json:"code,omitempty"`
	Lang       string                `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Proxy      string                `protobuf:"bytes,3,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Dependency *Dependency           `protobuf:"bytes,4,opt,name=dependency,proto3" json:"dependency,omitempty"`
}

func (x *DependencyServiceConnectResponse) Reset() {
	*x = DependencyServiceConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyServiceConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyServiceConnectResponse) ProtoMessage() {}

func (x *DependencyServiceConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyServiceConnectResponse.ProtoReflect.Descriptor instead.
func (*DependencyServiceConnectResponse) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{2}
}

func (x *DependencyServiceConnectResponse) GetCode() DependencyServiceCode {
	if x != nil {
		return x.Code
	}
	return DependencyServiceCode_SYNC
}

func (x *DependencyServiceConnectResponse) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *DependencyServiceConnectResponse) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *DependencyServiceConnectResponse) GetDependency() *Dependency {
	if x != nil {
		return x.Dependency
	}
	return nil
}

type DependencyServiceSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey      string        `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Lang         string        `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Dependencies []*Dependency `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *DependencyServiceSyncRequest) Reset() {
	*x = DependencyServiceSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyServiceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyServiceSyncRequest) ProtoMessage() {}

func (x *DependencyServiceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyServiceSyncRequest.ProtoReflect.Descriptor instead.
func (*DependencyServiceSyncRequest) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{3}
}

func (x *DependencyServiceSyncRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *DependencyServiceSyncRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *DependencyServiceSyncRequest) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type DependencyServiceUpdateLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId string   `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Logs     []string `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *DependencyServiceUpdateLogsRequest) Reset() {
	*x = DependencyServiceUpdateLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyServiceUpdateLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyServiceUpdateLogsRequest) ProtoMessage() {}

func (x *DependencyServiceUpdateLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyServiceUpdateLogsRequest.ProtoReflect.Descriptor instead.
func (*DependencyServiceUpdateLogsRequest) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{4}
}

func (x *DependencyServiceUpdateLogsRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DependencyServiceUpdateLogsRequest) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type DependencyDriver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DependencyDriver) Reset() {
	*x = DependencyDriver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyDriver) ProtoMessage() {}

func (x *DependencyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyDriver.ProtoReflect.Descriptor instead.
func (*DependencyDriver) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{5}
}

func (x *DependencyDriver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyDriver) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DependencyServiceSyncConfigSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeKey string              `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Lang    string              `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Version string              `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status  string              `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error   string              `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Drivers []*DependencyDriver `protobuf:"bytes,6,rep,name=drivers,proto3" json:"drivers,omitempty"`
}

func (x *DependencyServiceSyncConfigSetupRequest) Reset() {
	*x = DependencyServiceSyncConfigSetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_dependency_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependencyServiceSyncConfigSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyServiceSyncConfigSetupRequest) ProtoMessage() {}

func (x *DependencyServiceSyncConfigSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_dependency_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyServiceSyncConfigSetupRequest.ProtoReflect.Descriptor instead.
func (*DependencyServiceSyncConfigSetupRequest) Descriptor() ([]byte, []int) {
	return file_services_dependency_service_proto_rawDescGZIP(), []int{6}
}

func (x *DependencyServiceSyncConfigSetupRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *DependencyServiceSyncConfigSetupRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *DependencyServiceSyncConfigSetupRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DependencyServiceSyncConfigSetupRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DependencyServiceSyncConfigSetupRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DependencyServiceSyncConfigSetupRequest) GetDrivers() []*DependencyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_services_dependency_service_proto protoreflect.FileDescriptor

var file_services_dependency_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x15, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3a, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x1f,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xaf, 0x01, 0x0a, 0x20, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x83, 0x01, 0x0a,
	0x1c, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x34, 0x0a, 0x0c,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x22, 0x55, 0x0a, 0x22, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x40, 0x0a, 0x10, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xd2, 0x01, 0x0a, 0x27,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x30,
	0x0a, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x2a, 0x48, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x59, 0x4e,
	0x43, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x45, 0x54, 0x55, 0x50, 0x10, 0x03, 0x32, 0xcf, 0x02, 0x0a, 0x11, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5c, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x25, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3c,
	0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x28, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x52, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x2d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_dependency_service_proto_rawDescOnce sync.Once
	file_services_dependency_service_proto_rawDescData = file_services_dependency_service_proto_rawDesc
)

func file_services_dependency_service_proto_rawDescGZIP() []byte {
	file_services_dependency_service_proto_rawDescOnce.Do(func() {
		file_services_dependency_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_dependency_service_proto_rawDescData)
	})
	return file_services_dependency_service_proto_rawDescData
}

var file_services_dependency_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_dependency_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_dependency_service_proto_goTypes = []any{
	(DependencyServiceCode)(0),                      // 0: grpc.DependencyServiceCode
	(*Dependency)(nil),                              // 1: grpc.Dependency
	(*DependencyServiceConnectRequest)(nil),         // 2: grpc.DependencyServiceConnectRequest
	(*DependencyServiceConnectResponse)(nil),        // 3: grpc.DependencyServiceConnectResponse
	(*DependencyServiceSyncRequest)(nil),            // 4: grpc.DependencyServiceSyncRequest
	(*DependencyServiceUpdateLogsRequest)(nil),      // 5: grpc.DependencyServiceUpdateLogsRequest
	(*DependencyDriver)(nil),                        // 6: grpc.DependencyDriver
	(*DependencyServiceSyncConfigSetupRequest)(nil), // 7: grpc.DependencyServiceSyncConfigSetupRequest
	(*Response)(nil),                                // 8: grpc.Response
}
var file_services_dependency_service_proto_depIdxs = []int32{
	0, // 0: grpc.DependencyServiceConnectResponse.code:type_name -> grpc.DependencyServiceCode
	1, // 1: grpc.DependencyServiceConnectResponse.dependency:type_name -> grpc.Dependency
	1, // 2: grpc.DependencyServiceSyncRequest.dependencies:type_name -> grpc.Dependency
	6, // 3: grpc.DependencyServiceSyncConfigSetupRequest.drivers:type_name -> grpc.DependencyDriver
	2, // 4: grpc.DependencyService.Connect:input_type -> grpc.DependencyServiceConnectRequest
	4, // 5: grpc.DependencyService.Sync:input_type -> grpc.DependencyServiceSyncRequest
	5, // 6: grpc.DependencyService.UpdateLogs:input_type -> grpc.DependencyServiceUpdateLogsRequest
	7, // 7: grpc.DependencyService.SyncConfigSetup:input_type -> grpc.DependencyServiceSyncConfigSetupRequest
	3, // 8: grpc.DependencyService.Connect:output_type -> grpc.DependencyServiceConnectResponse
	8, // 9: grpc.DependencyService.Sync:output_type -> grpc.Response
	8, // 10: grpc.DependencyService.UpdateLogs:output_type -> grpc.Response
	8, // 11: grpc.DependencyService.SyncConfigSetup:output_type -> grpc.Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_dependency_service_proto_init() }
func file_services_dependency_service_proto_init() {
	if File_services_dependency_service_proto != nil {
		return
	}
	file_entity_response_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_dependency_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyServiceConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyServiceConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyServiceSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyServiceUpdateLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyDriver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_dependency_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DependencyServiceSyncConfigSetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_dependency_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_dependency_service_proto_goTypes,
		DependencyIndexes: file_services_dependency_service_proto_depIdxs,
		EnumInfos:         file_services_dependency_service_proto_enumTypes,
		MessageInfos:      file_services_dependency_service_proto_msgTypes,
	}.Build()
	File_services_dependency_service_proto = out.File
	file_services_dependency_service_proto_rawDesc = nil
	file_services_dependency_service_proto_goTypes = nil
	file_services_dependency_service_proto_depIdxs = nil
}
