// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: services/dependency_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DependencyService_Connect_FullMethodName         = "/grpc.DependencyService/Connect"
	DependencyService_Sync_FullMethodName            = "/grpc.DependencyService/Sync"
	DependencyService_UpdateLogs_FullMethodName      = "/grpc.DependencyService/UpdateLogs"
	DependencyService_SyncConfigSetup_FullMethodName = "/grpc.DependencyService/SyncConfigSetup"
)

// DependencyServiceClient is the client API for DependencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependencyServiceClient interface {
	Connect(ctx context.Context, in *DependencyServiceConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DependencyServiceConnectResponse], error)
	Sync(ctx context.Context, in *DependencyServiceSyncRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DependencyServiceUpdateLogsRequest, Response], error)
	SyncConfigSetup(ctx context.Context, in *DependencyServiceSyncConfigSetupRequest, opts ...grpc.CallOption) (*Response, error)
}

type dependencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDependencyServiceClient(cc grpc.ClientConnInterface) DependencyServiceClient {
	return &dependencyServiceClient{cc}
}

func (c *dependencyServiceClient) Connect(ctx context.Context, in *DependencyServiceConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DependencyServiceConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DependencyService_ServiceDesc.Streams[0], DependencyService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DependencyServiceConnectRequest, DependencyServiceConnectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DependencyService_ConnectClient = grpc.ServerStreamingClient[DependencyServiceConnectResponse]

func (c *dependencyServiceClient) Sync(ctx context.Context, in *DependencyServiceSyncRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DependencyService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyServiceClient) UpdateLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DependencyServiceUpdateLogsRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DependencyService_ServiceDesc.Streams[1], DependencyService_UpdateLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DependencyServiceUpdateLogsRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DependencyService_UpdateLogsClient = grpc.ClientStreamingClient[DependencyServiceUpdateLogsRequest, Response]

func (c *dependencyServiceClient) SyncConfigSetup(ctx context.Context, in *DependencyServiceSyncConfigSetupRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DependencyService_SyncConfigSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyServiceServer is the server API for DependencyService service.
// All implementations must embed UnimplementedDependencyServiceServer
// for forward compatibility.
type DependencyServiceServer interface {
	Connect(*DependencyServiceConnectRequest, grpc.ServerStreamingServer[DependencyServiceConnectResponse]) error
	Sync(context.Context, *DependencyServiceSyncRequest) (*Response, error)
	UpdateLogs(grpc.ClientStreamingServer[DependencyServiceUpdateLogsRequest, Response]) error
	SyncConfigSetup(context.Context, *DependencyServiceSyncConfigSetupRequest) (*Response, error)
	mustEmbedUnimplementedDependencyServiceServer()
}

// UnimplementedDependencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDependencyServiceServer struct{}

func (UnimplementedDependencyServiceServer) Connect(*DependencyServiceConnectRequest, grpc.ServerStreamingServer[DependencyServiceConnectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDependencyServiceServer) Sync(context.Context, *DependencyServiceSyncRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDependencyServiceServer) UpdateLogs(grpc.ClientStreamingServer[DependencyServiceUpdateLogsRequest, Response]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateLogs not implemented")
}
func (UnimplementedDependencyServiceServer) SyncConfigSetup(context.Context, *DependencyServiceSyncConfigSetupRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncConfigSetup not implemented")
}
func (UnimplementedDependencyServiceServer) mustEmbedUnimplementedDependencyServiceServer() {}
func (UnimplementedDependencyServiceServer) testEmbeddedByValue()                           {}

// UnsafeDependencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependencyServiceServer will
// result in compilation errors.
type UnsafeDependencyServiceServer interface {
	mustEmbedUnimplementedDependencyServiceServer()
}

func RegisterDependencyServiceServer(s grpc.ServiceRegistrar, srv DependencyServiceServer) {
	// If the following call pancis, it indicates UnimplementedDependencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DependencyService_ServiceDesc, srv)
}

func _DependencyService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyServiceConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyServiceServer).Connect(m, &grpc.GenericServerStream[DependencyServiceConnectRequest, DependencyServiceConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DependencyService_ConnectServer = grpc.ServerStreamingServer[DependencyServiceConnectResponse]

func _DependencyService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyServiceSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).Sync(ctx, req.(*DependencyServiceSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyService_UpdateLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DependencyServiceServer).UpdateLogs(&grpc.GenericServerStream[DependencyServiceUpdateLogsRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DependencyService_UpdateLogsServer = grpc.ClientStreamingServer[DependencyServiceUpdateLogsRequest, Response]

func _DependencyService_SyncConfigSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependencyServiceSyncConfigSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyServiceServer).SyncConfigSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyService_SyncConfigSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyServiceServer).SyncConfigSetup(ctx, req.(*DependencyServiceSyncConfigSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DependencyService_ServiceDesc is the grpc.ServiceDesc for DependencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DependencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DependencyService",
	HandlerType: (*DependencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _DependencyService_Sync_Handler,
		},
		{
			MethodName: "SyncConfigSetup",
			Handler:    _DependencyService_SyncConfigSetup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _DependencyService_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateLogs",
			Handler:       _DependencyService_UpdateLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "services/dependency_service.proto",
}
